#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master
    - release

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012 R2

# scripts that run after cloning repository
install:
  - cmd: git submodule update --init
  - cmd: nuget restore
  - ps:  .\prebuild.ps1
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

after_test:
  # Push artifacts and publish the nighly build to http://vsixgallery.com
  - ps: Vsix-PushArtifacts .\YamlDotNetEditor\bin\*\*.vsix | ? { $env:APPVEYOR_REPO_BRANCH -ne "release" } | Vsix-PublishToGallery
